apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge
  labels:
    app: challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge
  template:
    metadata:
      labels:
        app: challenge
    spec:
      containers:
        - name: challenge
          image: duiliofelix/devops-challenge:latest
          ports:
          - containerPort: 80
          envFrom:
          - secretRef:
              name: challenge-secret