name: Main Pipeline

on:
  pull_request:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '15.x'
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run lint
#      - run: npm run prettier
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '15.x'
      - uses: actions/checkout@v4
      - run: npm install
      - run: CI=true npm run test
  build:
    runs-on: ubuntu-latest
    needs:
    - lint
    - test
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '15.x'
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build